## usar o comando `make` para compilar tudo para a pasta `build`
## usar `make clean` para o diretório `build` criado

all:
	mkdir -p build
	javac -d build src/shared/*.java src/client/*.java src/server/*.java

clean:
	$(RM) -rf build
