sequenceDiagram
  participant Server
  participant Client

  Server->>Server: Open a socket
  Server->>Server: Name the socket
  Server->>Server: Listen for incoming client connections
  Client->>Client: Open a socket
  Client ->>+Server: Connect to server
  Server -->>-Client: Accept connection

  loop Every Click from GUI
    Client->>+Server: Send RPC identifier
    Server-->>-Client: Receive RPC identifier
    alt RP exists on server
      Server->>+Client: Send status "true"
      Client-->>-Server: Receive status
      Client->>+Server: Send procedure's input
      Server-->>-Client: Receive procedure's input
      Server->>Server: Run the called procedure
      Server->>+Client: Send result
      Client-->>-Server: Receive procedure's output
    else RP not found
      Server->>+Client: Send status "false"
      Client-->>-Server: Receive status
    end
  end

  Client->>Client: Close stream and connection